---
# tasks file for playbooks/roles/rhv_vm_create
- name: Authenticate to engine to obtain SSO token
  ovirt_auth:
    url: "{{ rhv_vm_auth_url | default(omit) }}"
    username: "{{ rhv_vm_auth_username | default(omit) }}"
    password: "{{ rhv_vm_auth_password | default(omit) }}"
    insecure: yes

- name: Remove VM {{ rhv_vm_hostname }}
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    state: absent
    name: "{{ rhv_vm_hostname }}"
    cluster: "{{ rhv_vm_cluster }}"

- name: Always revoke the SSO token
  ovirt_auth:
    state: absent
    ovirt_auth: "{{ ovirt_auth }}"
