galaxy_info:
  role_name: rhv-vm
  author: Mario Feliz
  description: >
    Create a VM on a Red Hat Virtualization (ovirt)
  company: Red Hat
  license: GPLv3
  min_ansible_version: 2.6
  platforms:
    - name: EL
      versions:
        - 7
#  galaxy_tags:
#    - cloud
#    - rhv
#    - ovirt
#    - rhel
#    - kvm

dependencies: []
